config/routes.rb
Earthvlab::Application.routes.draw do
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'
  
  resources :pages
  resources :news
  resources :achievements
  resources :infos
  resources :refers
  resources :resumes
  
  get 'search' => 'home#search'

  

end

app/controllers/home_controller.rb
require 'nokogiri'
class HomeController < ApplicationController
  def index
  end
  
  def search
    @q = params[:search]
    @pages = Page.where("title LIKE ? OR content LIKE ?", "%#{@q}%", "%#{@q}%").page params[:page]
    add_breadcrumb "首页", "/"
    add_breadcrumb "搜索"
    add_breadcrumb params[:search]
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def show_links
    Link.all.map{|link|link_to(link.name,link.url,{:target=>"_blank",style: "color: #06c;"})}.join(" | ").html_safe
  end
  
  def display_image message
    image = "#{message.class.name.downcase}.png"
    if message.has_thumb?
      image = message.thumb.url(:thumb)
    end
    image_tag image, {class: :message_image}
  end
end

app/views/home/index.html.erb
<script type="text/javascript">
	var colomatduration = 'fast';
	var colomatslideEffect = 'slideFade';
</script>
<body class="home page page-id-548 page-template page-template-front-page-itu-php">        
<div id="container" class="hfeed">
	   <%=render "layouts/header"%>
	   <div id="featured" class="grid col-960 frontwrapper">
		   <div id="soliloquy-container-471" class="soliloquy-container soliloquy-fade soliloquy-preloader" style="max-width: 960px; max-height: 400px; ">
			   <div id="soliloquy-471" class="soliloquy">
				  <ul id="soliloquy-list-471" class="soliloquy-slides">
      			  	<%Gallery.visiable.each_with_index do |gallery,i|%>
      				    <li id="soliloquy-471-item-<%=i+1%>" 
      				   		class="soliloquy-item" style="width: 100%; 
   								float: left; margin-right: -100%; position: relative; display: none;">
      					   <a href="/" title="">
      						  <%=image_tag gallery.avatar.url(:medium)%>
      					   </a>
      				    </li>
      				<%end%>
				  </ul>
		  	   </div>
			   <ul class="soliloquy-direction-nav">
				   <li><a class="soliloquy-prev" href="#">Previous</a></li>
				   <li><a class="soliloquy-next" href="#">Next</a></li>
			   </ul>
	        </div>
	    </div>
  
	    <div id="widgets" class="home-widgets">
	        <div class="grid col-480">
	                <h3 style="background-color: #65C5F9; padding: 10px; color:  #000; margin-bottom: 0px;">通知</h3>
					<div id="rpwe_widget-3" class="widget-wrapper rpwe_widget recent-posts-extended">
			<div class="rpwe-block">
				<ul>
					<%Info.recent.each do |info|%>
					<li class="rpwe-clearfix">
						<h3 class="rpwe-title">
							<%=link_to info.title, info_path(info)%>
						</h3>
						<span class="rpwe-time">发布于 <%= l info.created_at, format: :long %></span>
						<div class="rpwe-summary">
							<%=display_image info%>
							<%=info.plain_content%>
						</div>
					</li>
					<%end%>
					<%=link_to "查看更多", infos_path%>
				</ul>
			</div><!-- .rpwe-block - http://wordpress.org/extend/plugins/recent-posts-widget-extended/ -->
		</div>            
	   </div><!-- end of .col-480 fit -->
       <div class="grid col-480 fit">
       <h3 style="background-color: #65C5F9; padding: 10px; color:  #000; margin-bottom: 0px;">国际行业资讯</h3>
		<div id="rpwe_widget-3" class="widget-wrapper rpwe_widget recent-posts-extended">
	<div class="rpwe-block">
		<ul>
			<%Refer.recent.each do |refer|%>
				<li class="rpwe-clearfix">
				<h3 class="rpwe-title">
					<%=link_to refer.title, refer_path(refer) %> 
				</h3>
				<span class="rpwe-time">
					发布于 <%= l refer.created_at, format: :long %>
				</span>
				<div class="rpwe-summary">
					<%=display_image refer%>
					<%=refer.plain_content%>
				</div>
				</li>
			<%end%>
			<%=link_to "查看更多", refers_path%>
		</ul>
	</div><!-- .rpwe-block - http://wordpress.org/extend/plugins/recent-posts-widget-extended/ -->
	</div>            
     </div><!-- end of .col-480 fit -->
	 </div> <!--end of home-widgets-->
	 
		<div id="widgets" class="home-widgets">
	        <div class="grid col-480">
	        <h3 style="background-color: #108DDF; padding: 10px; color:  #FFF;font-weight: 700; margin-bottom: 0px;">新闻</h3>
	  		<div id="rpwe_widget-3" class="widget-wrapper rpwe_widget recent-posts-extended">
	  			<div class="rpwe-block">
	  		<ul>
	  			<%News.recent.each do |news|%>
	  				<li class="rpwe-clearfix">
	  				<h3 class="rpwe-title">
	  					<%=link_to news.title, news_path(news) %>
	  				</h3>
	  				<span class="rpwe-time">发布于 <%= l news.created_at, format: :long %></span>
	  				<div class="rpwe-summary">
						<%=display_image news%>
						<%=news.plain_content%>
	  				</div>
	  				</li>
	  			<%end%>
	  			<%=link_to "查看更多", news_index_path%>
	  		</ul>
	  		</div><!-- .rpwe-block - http://wordpress.org/extend/plugins/recent-posts-widget-extended/ -->
	  		</div>            
	      </div><!-- end of .col-480 fit -->
        
      <div class="grid col-480 fit">
      <h3 style="background-color: #108DDF; padding: 10px; color:  #FFF;font-weight: 700; margin-bottom: 0px;">
		最新成果展示	
	</h3>
	<div id="rpwe_widget-2" class="widget-wrapper rpwe_widget recent-posts-extended">
	<div class="rpwe-block">
		<ul>
			<%Achievement.recent.each do |achievement|%>
				<li class="rpwe-clearfix">
					<h3 class="rpwe-title">
						<%=link_to achievement.title, achievement_path(achievement)%>
					</h3>
					<span class="rpwe-time">
						发布于 <%= l achievement.created_at, format: :long %>
					</span>
					<div class="rpwe-summary">
						<%=display_image achievement%>
						<%=achievement.plain_content%>
					</div>
				</li>
			<%end%>
			<%=link_to "查看更多", achievements_path%>
		</ul>
	</div><!-- .rpwe-block - http://wordpress.org/extend/plugins/recent-posts-widget-extended/ -->
	</div>           
    </div><!-- end of .col-480 fit --> 
    </div><!-- end of #widgets -->
	<script type="text/javascript">
jQuery('#applicants-home select[name=00Ni0000005aQR4]').change(function(e){
  if (jQuery('#applicants-home select[name=00Ni0000005aQR4]').val() == 'Change of Status [Other Visa Type to F1]'){
    jQuery("select[name=00Ni0000005bBNB]").attr('required','');
      jQuery('#cos-home').fadeIn(300, function(){
      	jQuery('#cos-home').show();
      	/*jQuery('#addbgc').addClass( "bgc-home-form" );
      	jQuery('#addbgc').addClass( "text-color-onForm" );*/
      });
  }else{
    jQuery("select[name=00Ni0000005bBNB]").removeAttr('required','');
  	  jQuery('#cos-home').fadeOut(100, function(){
  	  	jQuery('#cos-home').hide();
  	  	/*jQuery('#addbgc').removeClass( "bgc-home-form" );
      	jQuery('#addbgc').removeClass( "text-color-onForm" );*/
      });
  }
});
</script>
		    </div><!-- end of #wrapper -->
    <!-- end of #container -->
		
<script type="text/javascript">
	jQuery(window).load(function(){
		jQuery('#soliloquy-471').flexslider({
		animation:'fade',slideshowSpeed:7000,animationDuration:600,
		controlsContainer:'#soliloquy-container-471',namespace:'soliloquy-',
		selector:'.soliloquy-slides > li',useCSS:false
		});
	});
</script>
				
</body>

app/views/home/search.html.erb
<div id="container" class="hfeed">
	<%=render "layouts/header"%>
	<div id="content" class="grid col-620">
		<div class="breadcrumb-list" xmlns:v="http://rdf.data-vocabulary.org/#">
			<%=render_breadcrumbs %>
		</div>
		<%@pages.each do |page|%>
			<div id="shortpost">
				<h1 class="post-title">
					<%=link_to page.title, page_path(page)%>
				</h1>                
			    <div class="post-entry">
			     	<p><%=page.plain_content%></p>
			    </div><!-- end of .post-entry -->
			</div>      
		<%end%>
		<%= paginate @pages %>  
	</div><!-- end of #content -->
	<div id="widgets" class="grid col-220 fit">
		<div id="text-13" class="widget-wrapper widget_text">
			<div class="widget-title">搜索关键词"<%=@q%>"</div>			
			</div>
			<%=image_tag "right_side.png"%>
			<div id="text-16" class="widget-wrapper widget_text">
				<div class="widget-title">更多链接</div>			
				<div class="textwidget">
					<a href="/">关于我们</a>
					<br/>
					<a href="/">联系我们</a>
				</div>
			</div>
	</div><!-- end of #widgets -->
</div>