config/routes.rb
Earthvlab::Application.routes.draw do
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'
  
  resources :pages
  resources :news
  resources :achievements
  resources :infos
  resources :refers
  resources :resumes
  
  get 'search' => 'home#search'

  

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user, :content
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def show
    add_breadcrumb "首页", root_path
    add_breadcrumb "教师简历", page_path(Setting.find_by(name: :resume).page)
    @resume = Resume.find(params[:id])
    add_breadcrumb @resume.user.name 
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_index.html.erb
<style>
table,td,th
{
border:0px solid black;
}
</style>
<%User::TITLES.each do |title|%>
	<%if User.with_title(title).any?%>
		<h3><%=title%></h3>
		<table>
			<tr>
			<%User.with_title(title).each_with_index do |user, i|%>
				<%if (i+1)%6==0%>
				</tr>
				<tr>
				<%end%>
				<td>
				<%if user.resumes.any?%>
					<%=link_to user.name, resume_path(user.resumes.first)%>
				<%else%>
					<%=user.name%>
				<%end%>
				</td>	
			<%end%>
			<%(0..User.with_title(title).length%5 - 1).each do |j|%>
				<td></td>
			<%end%>
			</tr>
		</table>
		<hr>
	<%end%>
<%end%>

app/views/resumes/show.html.erb
<div id="container" class="hfeed">
	<%=render "layouts/header"%>
<div id="content" class="grid col-620">
	<div class="breadcrumb-list" xmlns:v="http://rdf.data-vocabulary.org/#">
		<%=render_breadcrumbs %>
	</div>        
	<div id="post-" class="post-41 page type-page status-publish hentry">       
		<!--Removed the retreat loop-header command-->
	    <div class="post-entry">
			<div class="indent">
			</div>
			<%=@resume.content.html_safe%>
	    </div><!-- end of .post-entry -->
	</div>
</div><!-- end of #content -->
<div id="widgets" class="grid col-220 fit">
	<div id="text-13" class="widget-wrapper widget_text">
		<div class="widget-title"><%=@resume.user.name%></div>			
		</div>
		<%=image_tag "right_side.png"%>
		<div id="text-16" class="widget-wrapper widget_text">
			<div class="widget-title">更多链接</div>			
			<div class="textwidget">
				<a href="/">关于我们</a>
				<br/>
				<a href="/">联系我们</a>
			</div>
		</div>
</div><!-- end of #widgets -->
</div>